# Token configuration
security.jwt.token:
  secret-key: development
  expire-length: 7200000

# CORS
allowed-origins: http://localhost:4200

# Directory to store static files
models-path: /home/guillem/Desktop/ml-ci/evaluations

# RabbitMQ connection URL
rabbit-mq-url: amqp://wkkreopq:2Jtl4DVl9KRixiYFLS3C2Gu9kOcBts-H@gopher.rmq.cloudamqp.com/wkkreopq

# MlModule config
ml-module:
  user: MlModule
  pass: $2a$10$H9LSl1g2bVk7EbV/hXXbEeXjSqbHTEbbf94PZ3jVuV7SYZRXpl9Yq

# Observer Module
observer-module:
  user: ObserverModule
  pass: $2a$10$4vrlWL30POvdblMLryUJ0uQo8z7scDdybOf12VLG6wsNLFQS4YBH6


# File upload config
spring:
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB

  http.multipart.enabled: false
