# Token configuration
security.jwt.token:
  secret-key: production
  expire-length: 7200000

# CORS
allowed-origins: http://127.0.0.1

# Directory to store static files
models-path: /home/app/trained-models

# RabbitMQ connection URL
rabbit-mq-url: amqp://wkkreopq:2Jtl4DVl9KRixiYFLS3C2Gu9kOcBts-H@gopher.rmq.cloudamqp.com/wkkreopq

# MlModule config
ml-module:
  user: MlModule
  pass: MlModule

# File upload config
spring:
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB

  http.multipart.enabled: false
