version: "3.4"
services:  
  ml-ci-webservice:
    build: ./ml-ci-webservice/
    container_name: ml-ci-webservice
    env_file:
     - ./ml-module/docker.env
    ports:
      - "8080:8080"
    restart: on-failure

  ml-ci-client:
    build: ./ml-ci-client
    container_name: ml-ci-client
    environment:
     - PORT=80
     - PROFILE=production
    ports:
      - "80:80"
    restart: on-failure

  ml-ci-observer:
    build: ./ml-ci-observer
    container_name: ml-ci-client
    environment:
     - PROFILE=prod
    restart: on-failure

  ml-module:
    build: ./ml-module
    container_name: ml-module
    env_file:
     - ./ml-module/docker.env
    depends_on:
      - ml-ci-webservice
    links:
      - ml-ci-webservice

    restart: on-failure
    